### ISSUE TITLE
WebDriverError

### ISSUE THREAD

**Issue by matthewecampbell** [vertis/selenium-webdriver#8]
I am trying to run some tests with the latest version of the gem (3.0.1 I believe?) and using Firefox 46 and I kept getting the following error:

Selenium::WebDriver::Error::WebDriverError:
              Unable to find Mozilla geckodriver. Please download the server from        https://github.com/mozilla/geckodriver/releases and place it        somewhere on your PATH. More info at https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver.

It can be fixed if you use the 2.53.2 version of this gem.  Based on reading some other things that people have written on various sites, I believe it may have happened when trying to fix something on Windows and now it is breaking on my Linux machine.

**Comment by vertis** [comment]
@matthewecampbell This repository was a personal import of selenium-webdriver for use on a project a long time ago. Probably the best place to raise this issue is the issues section for: 

https://github.com/SeleniumHQ/selenium/tree/master/rb.

Hope you get the issue sorted out.

**Comment by matthewecampbell** [comment]
Thanks @vertis!  Sorry for the confusion.
